### ISSUE TITLE
XDebug support writeup?

### ISSUE THREAD

**Issue by EMCP** [juriansluiman/SlmQueue#149]
I am now happily utilizing `SlmQueue` via `Beanstalkd` , with one problem.

XDebug is halting on regular calls made to my ZF2 application, but Queue'd Job code is not..  Any ideas why?  Do I need to pass a flag on startup of the Queue Worker?

I'll be glad to write up more once I get it working.  Does the Queue worker use `/etc/php5/cli` runtime?

`/etc/php5/apache2/php.ini`

```
zend.enable_gc = On
zend_extension=/usr/lib/php5/20121212/xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_connect_back=1
xdebug.remote_host=10.10.10.1
xdebug.remote_port=9000
xdebug.idekey=PHPSTORM
```

**Comment by kusmierz** [comment]
put this code into `/usr/bin/xdebug`:

```bash
#!/bin/bash
PHP_IDE_CONFIG="serverName=`echo $HOSTNAME`.cli" XDEBUG_CONFIG="idekey=xdebug" php -dxdebug.remote_autostart=1 -didekey=xdebug -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_host=`who am i | awk '{print $5}' | sed 's/[()]//g'` "$@"
```

next you can run `xdebug public/index.php queue [...]`. Good luck!

**Comment by ltouro** [comment]
my IDE starts XDebug with CLI like this
C:\xampp\php\php.exe -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1 index.php queue doctrine LtEmail\Queue\EmailQueue --start
