### ISSUE TITLE
Strategy doubles

### ISSUE THREAD

**Issue by malinink** [juriansluiman/SlmQueue#164]
It is feature? when the same strategy defined twice:

```php
worker_strategies' => [
            'default' => [
                    'SlmQueue\Strategy\MaxMemoryStrategy'   => ['max_memory' => 10 * 1024 * 1024],
            ],
            'queues' => [
                'default' => [
                ],
                'email' => [
                    'SlmQueue\Strategy\ProcessQueueStrategy',
                    'SlmQueue\Strategy\MaxMemoryStrategy'   => ['max_memory' => 30 * 1024 * 1024],
                ],
            ],
],
``` 

It cause two separate `MaxMemoryStrategy` strategy attached to Queue, so I have double memory checks.

I don't really know is that normal way it should work, so I decided to ask that here.

**Comment by basz** [comment]
Yes, this is the expected behavior. I found this not very handy either. But for some reason - that I can't remember exactly right now - things turned out this way...

**Comment by malinink** [comment]
Thanks, it wasn't clean for me!
