### ISSUE TITLE
Where to add event listener

### ISSUE THREAD

**Issue by itailulu** [juriansluiman/SlmQueue#171]
It's not clear (at least for me) where you suppose to attach event listeners (specifically i'm referring to https://github.com/juriansluiman/SlmQueue/blob/master/docs/6.Events.md#do-something-before-or-after-the-processing-of-a-job)
Can anyone shed some light on the subject?

**Comment by basz** [comment]
You would start by creating an aggregate listener class with code as in your link above. Step two is adding that aggregate listener to the event listener. onBootstrap in your module.php is a good place to do that.

Have a look at this in depth [article](http://www.michaelgallego.fr/blog/2013/05/12/understanding-the-zend-framework-2-event-manager/) on the event manager.
