### ISSUE TITLE
Clarify unit and how to set maxpollingfrequencystrategy

### ISSUE THREAD

**Issue by antonycox** [juriansluiman/SlmQueue#176]
Hi. Can you confirm what value should be used, and how is it set? For example, how would you define a frequency of once a minute? And where should you set that value (whatever it is?)

```
'my-queue' => [
         MaxPollingFrequencyStrategy::class => [ 'max_frequency' => 100 ],
         ]
```

Thanks in advance for clarification.

**Comment by basz** [comment]
Have you read [this](https://github.com/juriansluiman/SlmQueue/blob/9a50503af11a708cfb80a6031d2d88a924459744/docs/6.Events.md#maxpollingfrequencystrategy)? If I read that correctly 'once every minute' would require a value of '0.0167'.
