### ISSUE TITLE
Allow binary data for job contents

### ISSUE THREAD

**Issue by kokx** [juriansluiman/SlmQueue#188]
Currently, it is impossible to put binary data in a job. `unserialize` will work fine with this, and correctly serialize this data. However, `json_encode` will give the following error:

```
Malformed UTF-8 characters, possibly incorrectly encoded
```

**Comment by basz** [comment]
you could base_encode before you place it on the job content and base_decode when you need the data inside the job.

**Comment by kokx** [comment]
That is indeed a solution. However, that makes things much more complicated when you are passing objects (obtained from external libraries) into a job, for which it is much harder to cleanly use `base64_encode` on their internal (binary) data.

**Comment by basz** [comment]
I have a couple of concerns with this addition

1. it breaks compatibility with existing queued jobs.
2. increases size of ALL jobs by 33%.
2. but more importantly base64 serialises in a way the makes it 'impossible' to inspect for ALL jobs... 
I use the doctrine adapter myself and routinely inspect rows in the database while debugging.

to counter your argument above; this is not complicated...
```
$job->setContent(base64_encode(serialize($obj)));
```

That said, we could also introduce a 'BinaryMessageInterface' and when a Job implements that interface the payload is base64'ed. This way we avoid a BC and users can selectively decided which jobs can contains a binary payload...

**Comment by kokx** [comment]
I completely see your concerns, and actually I've had those concerns myself as well.

I think that introducting `BinaryMessageInterface` for jobs would be a great solution for this. I will work this into the PR.

**Comment by bakura10** [comment]
I agree. This is a massive BC. We did that at the beginning of the library but now it has so many users I'd like if we could find another way. The idea of "BinaryMessageInterface" is better imho.

**Comment by jackdpeterson** [comment]
I personally wouldn't mind a BC with a new version number.  if we could get rid of the php's serialization method (optionally, but retain as a default) and wrap that functionality in a serializing / unserializing interface then that's be great IMHO. The perspective I'm thinking about is if someone is supporting a project that has back-end(s) in multiple languages (e.g., PHP and Java) ... having a more portable data format would make things easier to port from one project to the other and vice versa. When performance requirements make sense ... being able to drain the queue in various languages without having to reinvent the job-submission wheel would be nice.
