### ISSUE TITLE
Cannot use 'String' as class name as it is reserved in phar

### ISSUE THREAD

**Issue by iit2011081** [juriansluiman/SlmQueue#194]
When I tried to install using composer I get this error "Cannot use 'String' as class name as it is reserved in phar". Is it because the library is incompatible with php7 ?

**Comment by basz** [comment]
No I use this lib with php 7.1 without issues

**Comment by iit2011081** [comment]
Any solution ?

**Comment by basz** [comment]
Try composer.phar selfupdate

**Comment by iit2011081** [comment]
I already tried but it says  Command "self-update" is not defined.

**Comment by basz** [comment]
Seems you a very old composer version. Simply download the latest one

**Comment by iit2011081** [comment]
I tried updating it but it says composer is already the newest version

**Comment by basz** [comment]
Ok, could tell me exactly what you are doing. Do you get any other information then the mentioned error message? Try running composer in verbose mode.

**Comment by iit2011081** [comment]
I am getting this error when i tried to install the library. How to run it in verbose mode ?
PHP Fatal error:  Cannot use 'String' as class name as it is reserved in phar:///my_project_folder/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/String.php on line 18

Fatal error: Cannot use 'String' as class name as it is reserved in phar:///my_project_folder/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/String.php on line 18

**Comment by basz** [comment]
https://getcomposer.org/doc/03-cli.md#global-options

What php version are you using?

php -v

**Comment by iit2011081** [comment]
php 7

**Comment by basz** [comment]
I have no idea what your issue is, but it seems unrelated to slmqueue

**Comment by iit2011081** [comment]
Closing the issue as it is related to composer not with the library
