### ISSUE TITLE
If I just want to use Beanstalkd then can i use only SlmQueueBeanstalkd

### ISSUE THREAD

**Issue by iit2011081** [juriansluiman/SlmQueue#197]
I want to use Beanstalkd for queue so can I use only SlmQueueBeanstalkd or do I need to also use SlmQueue.  I am using SlmQueueBeanstalkd but getting error.

In the controller I have created following things according to the document
```
protected $queue;
	
	public function __construct(QueueInterface $queue) {
		$this->queue = $queue;
	}

public function fooAction()
    {
        $job = new EmailJob;
        $job->setContent(array(
            'to'      => 'john@doe.com',
            'subject' => 'Just hi',
            'message' => 'Hi, I want to say hi!'
        ));
        $this->queue->push($job, ['delay' => 60]);
    }

In module.config.php I have define a route like this
'email' => array (
        			'type' => 'Zend\Mvc\Router\Http\Literal',
        			'options' => array (
        					'route' => '/email',
        					'defaults' => array (
        							'controller' => 'Application\Controller\Index',
        							'action' => 'foo'
        					)
        			),
        	),
```
When I go to the url /email it is showing 500 error because the constructor is expecting one argument and I am not passing any argument. When I try to run following command 
php index.php queue beanstalkd default
The result I am getting is 
```
Zend Framework 2.3.3 application
Usage:

Reason for failure: Invalid arguments or no arguments provided 
```

**Comment by basz** [comment]
SlmQueueBeanstalkd requires SlmQueue. It can not work without it.

To use the queue inside of an controller, you can use a [controller](https://github.com/juriansluiman/SlmQueue/blob/master/src/Controller/Plugin/QueuePlugin.php
) plugin. Simply call `$this->queue()->push($job)` within an controller. There is no need to inject dependency yourself. You *could* but then you should provide a factory.

Regarding the `php index.php queue beanstalkd default` error. That could be related to there things in your application. You should configure your application to throw more debug information before I can help to pin it down to something SlmQueueBeanstalkd related.

**Comment by iit2011081** [comment]
I installed SlmQueueBeanstalkd and I think it will automatically install SlmQueue. This is my directory structure and check everything is installed or not ?
![imageedit_2_2898010272](https://cloud.githubusercontent.com/assets/9371846/24353737/a3cda39c-130c-11e7-9681-2832caa1c814.jpg)

**Comment by basz** [comment]
yup, thats correct

**Comment by iit2011081** [comment]
Is there anything which I need to install ? I am still getting the same error

**Comment by basz** [comment]
For the controller action or the cli command?

Did you configure to display exceptions? That will tell you what part is problematic...

**Comment by iit2011081** [comment]
For the controller action. I don't know how to configure display exceptions. The problem is I have defined following constructor in the controller.
```
public function __construct(QueueInterface $queue) {
		$this->queue = $queue;
	} 
```
So obviously it will show error When I go to the url /email  because the constructor is expecting one argument and I am not passing any argument.

**Comment by basz** [comment]
you do not need to inject the service into your controller as in controllers have a melanism called plugins for we provide a one called `queue`. simply remove that constructor (arguments)

> To use the queue inside of an controller, you can use a controller plugin. Simply call $this->queue()->push($job) within an controller. There is no need to inject dependency yourself. You could but then you should provide a factory.

**Comment by iit2011081** [comment]
It is showing Call to a member function push() on null when I use $this->queue()->push($job) with the controller. When you say "To use the queue inside of an controller, you can use a controller plugin", How to use the controller plugin, is it already installed with my setup(see pic which I shared earlier) ?

**Comment by basz** [comment]
that means the plugin wasn't registered correctly

if you run `composer show` what do you see?

did you add the module to the application configuration in `config/application.config.php`?

```
return [
    'modules' => [
        ... // other modules
        'SlmQueue',
        'SlmQueueDoctrine',
    ],
    ....

```

**Comment by iit2011081** [comment]
When I run composer show it is showing following things
```
pda/pheanstalk              v3.1.0 PHP client for beanstalkd queue
slm/queue                   0.5.1  Zend Framework 2 module that integrates with various queue management systems
slm/queue-beanstalkd        v0.4.0 Zend Framework 2 module that integrates with Beanstalkd queuing system
zendframework/zendframework 2.3.1  Zend Framework 2
zendframework/zendxml       1.0.2  Utility library for XML usage, best practices, and security in PHP
```
and this is my config/application.config.php

```
<?php
return array(
    'modules' => array(
        'Application',
    ),

    // These are various options for the listeners attached to the ModuleManager
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
    ),
);

```
vendor is already included in module_paths , do I still I need to include SlmQueue in my application.config file ?

**Comment by basz** [comment]
Yes you must 'register' zend modules as such into the zend mvc layer.

The vendor directory is auto load able by php. 

Please see my previous example but replace doctrine with beanstalk. Place that after the 'Application' entry in 'modules'.

**Comment by iit2011081** [comment]
I done what you said, still getting same error. 
Now my application.config file is like this
```
<?php
return array(
    'modules' => array(
        'Application',
        'SlmQueue',
        'SlmQueueBeanstalkd',
    ),

    // These are various options for the listeners attached to the ModuleManager
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
    ),
);
```
This is my controller 
```
class IndexController extends AbstractActionController
{
	protected $modelObj;
	
    public function indexAction()
    {
    	
        return new ViewModel();
    }
    
    public function fooAction()
    {
    	// Do some work
    
    	$job = new EmailJob;
    	$job->setContent(array(
    			'to'      => 'johndoe@gmail.com',
    			'subject' => 'Just hi',
    			'message' => 'Hi, I want to say hi!'
    	));
    	$this->queue->push($job, ['delay' => 60]);
    }
}
```
My controller is extending AbstractActionController i.e. why $this-queue is unknown to this controller.

**Comment by basz** [comment]
That's because you do not invoke the plugin correctly, see https://github.com/juriansluiman/SlmQueue/blob/master/src/Controller/Plugin/QueuePlugin.php#L56

it's signature is `->queue($name)`, so your actions would become

```
 public function fooAction()
    {
    	// Do some work
    
    	$job = new EmailJob;
    	$job->setContent(array(
    			'to'      => 'johndoe@gmail.com',
    			'subject' => 'Just hi',
    			'message' => 'Hi, I want to say hi!'
    	));
    	$this->queue('default')->push($job, ['delay' => 60]);
    }
```

**Comment by iit2011081** [comment]
Now it is showing 
```
SlmQueue\Controller\Exception\QueueNotFoundException
File:
/var/www/Test-ZF2/vendor/slm/queue/src/Controller/Plugin/QueuePlugin.php:60
Message:
Queue 'default' does not exist
```

**Comment by basz** [comment]
you need to configure queue's https://github.com/juriansluiman/SlmQueue/blob/master/config/module.config.php#L57

did you read the documentation?

**Comment by iit2011081** [comment]
I read the documentation and done the following things:
Copy file slm_queue_beanstalkd.local.php.dist to config/autoload and rename it to slm_queue_beanstalkd.local.php. In this I don't need to change the configurations.

Then I copy the slm_queue.global.php.dist file to config/autoload and rename it to slm_queue.global.php and changed the following things:
```
 'queues' => ['default'],
'queue_manager' => ['SlmQueueBeanstalk']
```
In my module.config.php I added following code:
```
'slm_queue' => array(
		'queue_manager' => array(
			'factories' => array(
				'email' => 'SlmQueueBeanstalkd\Factory\BeanstalkdQueueFactory'
			)
		)
	),
```
Are these configurations correct?

**Comment by basz** [comment]
Almost, you are trying to add a queue named `email`. 

    'slm_queue' => [
        'queues'            => [
            'email' => [
                // options for the BeanstalkdQueueFactory uses to instantiate a queue
            ]
        ],

you could change `slm_queue.global.php` to include this directly, no need to add it to your `module.config.php`. 

        'queue_manager'     => [
            'factories' => [
                'email' => \SlmQueueBeanstalkd\Factory\BeanstalkdQueueFactory::class,
            ],
        ],

This is wrong anyhow (any key ending in '_manager' should have only keys allowed by the zend-servicemanager (factories, etc...)

    'queue_manager' => ['SlmQueueBeanstalk']

**Comment by iit2011081** [comment]
Sorry for replying after a long time. I removed everything and tried to use it from start and I think I am near to completion (unlike earlier I am not getting internal server error), but I am getting NULL response when pushing job in the queue.

```
$queueManager = $this->serviceLocator->get('SlmQueue\Queue\QueuePluginManager');
    	$queue = $queueManager->get('email');
    	$job = new EmailJob;
    	$job->setContent(array(
    			'to'      => 'john@doe.com',
    			'subject' => 'Just hi',
    			'message' => 'Hi, I want to say hi!'
    	));
    	$response = $queue->push($job, ['delay' => 60]);
    	var_dump($response); //giving NULL
```
In my module.config.php I have added this
```
'slm_queue' => array(
		'queue_manager' => array(
			'factories' => array(
				'email' => 'SlmQueueBeanstalkd\Factory\BeanstalkdQueueFactory'
			)
		)
	),
```
I don't know which command to run first,
route one which is responsible for pushing job in queue 
or 
beanstalkd command . 

When I run below command it is giving me some error.
```
php index.php queue beanstalkd email
Zend Framework 2.3.5 application
Usage:

Reason for failure: Invalid arguments or no arguments provided
```

**Comment by basz** [comment]
Null is correct as nothing is support to be returnwedstrijd by 'push'. See https://github.com/juriansluiman/SlmQueue/blob/master/src/Queue/QueueInterface.php

As for the Error I cant yell from this Error but im thinking you are missing Some configuration option for beanstalk. Enable exception tracing when you are developing. It will tell exactly where the error comes from and gives clues about how to fix it.

Use https://github.com/zendframework/ZendDeveloperTools
But first try to enable this setting https://github.com/zendframework/ZendSkeletonApplication/blob/master/config/autoload/development.local.php.dist

**Comment by basz** [comment]
Oh and on the 'order'. You normally start a worker and keep it running (manual is fine for development in production you would use something like supervisor). The worker will query the beanstalk server for any available job to be executed. Then in application you push jobs to the queue whenever you need to. So the order in which you run them should not matter. Job -> queue -> worker

**Comment by iit2011081** [comment]
@basz Thanks a lot, it was my bad I was running php index.php queue beanstalkd email on my some other application not the one in which I am working right now, so stupid I am, finally working. Once again thanks.

**Comment by iit2011081** [comment]
One more things, what is supervisor and how to use it, any link ?

**Comment by basz** [comment]
good! pls close issue if you feel it has been resolved

https://serversforhackers.com/c/monitoring-processes-with-supervisord

**Comment by iit2011081** [comment]
I am unable to use $queueManager in any other module except Application module. On var_dump it is showing null while it give me some object when I use the same in Application module. Do I need to change anything to use it in other modules.
`$queueManager = $this->serviceLocator->get('SlmQueue\Queue\QueuePluginManager');`

**Comment by basz** [comment]
no, it should work. 

I think something else is happening because if a service isn't registered an exception is thrown when you by the serviceLocator.

Also make sure you are getting it from the correct serviceLocator. Sometime the context (eg.  from with a controller) is different then the main one. You can get to the parent by using `$this->serviceLocator->getServiceLocator()`.

Another tip: are you sure `$this->serviceLocator` isn't null?
