### ISSUE TITLE
How to push one job from inside of another job ?

### ISSUE THREAD

**Issue by iit2011081** [juriansluiman/SlmQueue#205]
Till now I am pushing job in a queue from controller but I also want to push one job from another job. The main problem here is access of QueuePluginManager. I can access  QueuePluginManager in controller like this `$this->serviceLocator->get('SlmQueue\Queue\QueuePluginManager')` , but how to access it within a Job, is it possible ?

**Comment by basz** [comment]
Make your job implement the [queue aware interface](https://github.com/juriansluiman/SlmQueue/blob/master/src/Queue/QueueAwareInterface.php). Then you are able to push a nee job from within a running job.
