### ISSUE TITLE
Remove ZF2 from repo tagline

### ISSUE THREAD

**Issue by roelvanduijnhoven** [juriansluiman/SlmQueue#206]
We should reflect that this repo works also on ZF3. I would suggest simply dropping the 2.

See:
![schermafdruk van 2017-10-17 16-16-33](https://user-images.githubusercontent.com/91910/31669870-920d7be2-b356-11e7-8e7e-3a4c1a76143d.png)

**Comment by basz** [comment]
we should, but i'm not the repo owner, just a mere contributor with commit rights. Don't think I can get to settings...  /cc @juriansluiman

**Comment by juriansluiman** [comment]
I changed the tagline. Because I am not active in the php community anymore, I can change ownership as well. If any want to volunteer, let me know.

**Comment by basz** [comment]
I volunteer jurian

**Comment by roelvanduijnhoven** [comment]
Me and team would be willing to help.

We have been contributing to this product as we are actively using it. We are utilizing multiple queue's for all sorts of reasons. One idea could be to host the repo as part of that organization: https://github.com/jouwweb. 

But I do not want to get in the way of @basz. Just an idea!

**Comment by basz** [comment]
As long as the project stays maintained I really don't mind which way we go. I would like to stay contributor. Perhaps a team supporting this would be best...

**Comment by roelvanduijnhoven** [comment]
Then are goals are properly aligned ;)..

Anyways: I was not planning on doing anything radical. So contributors would stay in place. And you still have direct commit permission and authority. I hope the people that are actively involved keep doing so. In fact: I hope on some good discussion with y'all as we maintain this thing!

**Comment by roelvanduijnhoven** [comment]
This repo is currently lacking attention. See for example the wonderful PR https://github.com/juriansluiman/SlmQueue/pull/209 that is being ignored.

Maybe this is a good time to actually move the repository. According to https://github.com/juriansluiman/SlmQueue/pull/209 it is as simple as moving the repository to the `JouwWeb` organization and updating the url on packagist.

@juriansluiman @basz Agree? 

@basz Do you see problems with the way I described the transfer procedure?

**Comment by basz** [comment]
It is true attention is lacking... (sorry) I don't mind transfering. However I don't think you can rename a composer package. So, why not commit rights for you?

**Comment by roelvanduijnhoven** [comment]
@basz Making you and me Admin for this repo would work as well I guess. 

It really depends on what @juriansluiman wants to do this this repo. I also don't mind keeping it here, as long as we can keep it better maintained. 

> However I don't think you can rename a composer package. So, why not commit rights for you?

Related to that. The name could be identical. Namely `SlmQueue`. But it would reside under https://github.com/JouwWeb/SlmQueue.

**Comment by juriansluiman** [comment]
I can transfer the repo, as I have (almost) zero time for php, so maintaining something is not possible anymore. Transferring is preferred to give contributors full access to all they need instead of managing settings via me. If OK, I'll transfer to JouwWeb. Let me know if anything has to happen about composer.

**Comment by juriansluiman** [comment]
BTW, I tried transfering to basz but as he had already a repo SlmQueue, that failed. Failure to me to make any notice about this. JouwWeb/SlmQueue is free, otherwise @basz  has to rename his SlmQueue first

**Comment by roelvanduijnhoven** [comment]
Regarding any changes necessary. Besides the transfer to JouwWeb; can you add me and @basz on Packagist as maintainer? With that and access to the repo we should have enough access to make sure the migration goes smoothly.

**Comment by juriansluiman** [comment]
Packagist: done
Transfer: "You don’t have the permission to create repositories on JouwWeb" ?

**Comment by roelvanduijnhoven** [comment]
@juriansluiman Made you part of our team. Does that help?

**Comment by juriansluiman** [comment]
Nope, not sure what happens. Earlier I've transferred to @basz which went ok. I can transfer to @roelvanduijnhoven personal account, so you can transfer in into JouwWeb. However, you also have a personal SlmQueue which you have to rename first (just like bas otherwise)

**Comment by roelvanduijnhoven** [comment]
@juriansluiman Removed my forks.

**Comment by juriansluiman** [comment]
@roelvanduijnhoven had to accept your invite first... Transfer done now to JouwWeb, you can remove me from the team :)
